#!/usr/bin/env python

# Summary: manage the RESTful service on all blenderfarm nodes
# Usage: blenderfarm server-manage [start|stop]
#---	

import sys, os
import config
sys.path.append("/usr/local/lib/python2.7/site-packages")
from novaclient.client import Client

config = config.getConfig()

# Provide blenderfarm completions	
if (sys.argv[1] == "--complete"):
	print "start stop"
	exit()


def main():
	action = sys.argv[1]
	nova = Client(2, os.environ['OS_USERNAME'], os.environ['OS_PASSWORD'], os.environ['OS_TENANT_NAME'], os.environ['OS_AUTH_URL'])
	for server in nova.servers.list():
		ipv6_address = server.networks['cybera'][1] 
		print server.name + ": "+action
		#os.system("ssh -i %s ubuntu@%s 'hostname'" % (os.environ['SSH_IDENTITY'], ipv6_address))


if __name__ == "__main__":
	main()
