#!/usr/bin/env bash
set -e

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: blenderfarm completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "blenderfarm-$COMMAND" || true)"

# Support sh commands too
if [ ! -x "$COMMAND_PATH" ]; then
	COMMAND_PATH="$(command -v "blenderfarm-sh-$COMMAND")"
fi

if grep -i "^# provide blenderfarm completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
